#!/usr/bin/env python3
"""Materialize trusted, reproducible audio before opening Godot. No network access."""
import argparse
import hashlib
import json
import os
from pathlib import Path
import sys
import tempfile

from generate_audio import ROOT, generate


def ensure_assets(root=ROOT, *, regenerate=False, renderer=generate):
    expected = json.loads((root / 'manifest.json').read_text())
    names = {'harbor', 'keeper_house', 'archive', 'lantern_room', 'tide_cave', 'watch_theme', 'bell_release'}
    if set(expected) != names:
        raise ValueError('Audio manifest does not identify the seven supported generated assets.')
    missing, changed = [], []
    for name in sorted(names):
        path = root / (name + '.wav')
        if not path.exists():
            missing.append(name)
        elif path.is_symlink() or hashlib.sha256(path.read_bytes()).hexdigest() != expected[name]['sha256']:
            changed.append(name)
    if changed and not regenerate:
        raise ValueError('Generated audio was modified: ' + ', '.join(changed) +
                         '. Preserve custom audio outside Assets/Audio, then rerun with --regenerate to replace these generated files.')
    if not missing and not changed:
        print('Audio setup: all seven assets already match; no files changed.')
        return
    # Build and validate the complete candidate first. Generator failure preserves existing files.
    with tempfile.TemporaryDirectory(prefix='.audio-build-', dir=root) as temporary:
        staging = Path(temporary)
        actual = renderer(staging)
        if actual != expected:
            raise ValueError('Generated audio does not match the committed manifest; existing assets were preserved.')
        for name in sorted(names):
            path = staging / (name + '.wav')
            if hashlib.sha256(path.read_bytes()).hexdigest() != expected[name]['sha256']:
                raise ValueError('Generated bytes failed manifest verification: ' + name)
        for name in missing + changed:
            os.replace(staging / (name + '.wav'), root / (name + '.wav'))
    print('Audio setup: generated and verified ' + str(len(missing + changed)) + ' assets.')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--regenerate', action='store_true', help='Explicitly replace modified generated WAVs after preserving custom work elsewhere.')
    options = parser.parse_args()
    try:
        ensure_assets(regenerate=options.regenerate)
    except (OSError, ValueError, KeyError, TypeError) as error:
        print('Audio setup failed: ' + str(error), file=sys.stderr)
        return 1
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
