Section "ServerFlags"
    Option "AutoAddDevices" "false"
    Option "DontVTSwitch" "true"
    Option "AllowMouseOpenFail" "true"
EndSection
Section "Device"
    Identifier "LanternwakeOwnedDummy"
    Driver "dummy"
    VideoRam 262144
EndSection
Section "Monitor"
    Identifier "LanternwakeOwnedMonitor"
    HorizSync 28-85
    VertRefresh 48-75
    Modeline "1440x900" 106.50 1440 1520 1672 1904 900 903 909 934 -hsync +vsync
EndSection
Section "Screen"
    Identifier "LanternwakeOwnedScreen"
    Device "LanternwakeOwnedDummy"
    Monitor "LanternwakeOwnedMonitor"
    DefaultDepth 24
    SubSection "Display"
        Depth 24
        Modes "1440x900"
    EndSubSection
EndSection
